# action.yml
name: 'Semver'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
random-number:
    description: "Greeting content"
    value: ${{ steps.greeting.outputs.content }}
runs:
  using: 'compose'
  steps:
    - name: greeting
      shell: bash
      run: |
        echo 123
        echo ${{ github.action_path }}
        echo helllo ${{inputs.who-to-greet}}
        OUTPUT=helllo ${{inputs.who-to-greet}}
        echo "::set-output name=content::$(echo $OUTPUT)"
      
